controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

index:
    path: /accueil
    methods: ["GET"]
    controller: App\Controller\DefaultController::index

locataire:
    path: /locataire
    methods: ["GET"]
    controller: App\Controller\DefaultController::locataire

modifLocataire:
    path: /locataire/modifLocataire
    methods: ["GET"]
    controller: App\Controller\DefaultController::modifLocataire

addLocataire:
    path: /locataire/addLocataire
    methods: ["GET"]
    controller: App\Controller\DefaultController::addLocataire



mandataire:
    path: /mandataire
    methods: ["GET"]
    controller: App\Controller\DefaultController::mandataire

modifMandataire:
    path: /mandataire/modifMandataire
    methods: ["GET"]
    controller: App\Controller\DefaultController::modifMandataire

addMandataire:
    path: /mandataire/addMandataire
    methods: ["GET"]
    controller: App\Controller\DefaultController::addMandataire

app_logout:
    path: /logout
    methods: GET